- type: application/vnd.org.wtwta.project
  name: Arduino-docs
  main: arduino-docs
  id: arduino-docs
  repositories:
    github: git@github.com:bvberkum/Arduino-docs.git
    dotmpe.origin: domains/dotmpe.com/htdocs/git/arduino-docs.git
  pd-meta:
    log: log/
    #DevLog.rst
  scripts:
    init:
      - htd package update
      - htd package remotes-reset
      - vc regenerate
