#!/bin/bash

cb=$(git st|head -1|awk 'NF>1{print $NF}')

target_prefix=$1
repo_branch=$2
source_prefix=$3

[ ! -e $target_prefix ] || { exit 2; }

temp_branch=_${repo_branch////-}_${source_prefix////-}

echo $1 $2 $3 > .${target_prefix////-}.gitprototype

git co $repo_branch
echo git subtree split --squash --prefix=$source_prefix $temp_branch
git subtree split --squash --prefix=$source_prefix -b $temp_branch
#git co $cb
#mkdir $target_prefix && git add $target_prefix
#git subtree merge --prefix=$target_prefix $temp_branch
